version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poetry
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#   server:
#     build:
#       context: ./apps/server
#     ports:
#       - "4000:4000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://postgres:postgres@db:5432/ifs
#     volumes:
#       - ./apps/server:/app

#   web:
#     build:
#       context: ./apps/web
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./apps/web:/app

# volumes:
#   pgdata: