version: '3.8'

services:
  # server (NestJS)
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: poetry-server
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/poetry
      - EMBEDDING_SERVICE_URL=http://embedding-server:4001
    depends_on:
      - postgres
    networks:
      - poetry-network

  # web (Next.js)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: poetry-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://server:4000
    depends_on:
      - server
    networks:
      - poetry-network

  # embedding-server (FastAPI)
  # embedding-server:
  #   build:
  #     context: .
  #     dockerfile: apps/embedding-server/Dockerfile
  #   container_name: poetry-embedding-server
  #   restart: always
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   volumes:
  #     - embedding_models:/root/.cache/huggingface/hub
  #   depends_on:
  #     - postgres
  #   networks:
  #     - poetry-network

volumes:
  embedding_models:

networks:
  poetry-network:
    driver: bridge