services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: always
    init: true
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/umami
      APP_SECRET: umami
    depends_on:
      - postgres
    networks:
      - poetry-network

networks:
  poetry-network:
    external: true