export enum PermissionEnum {
  CREATE_USER = 'createUser',
  DELETE_USER = 'deleteUser',
  UPDATE_USER = 'updateUser',
  VIEW_DETAIL_USER = 'viewDetailUser',
  VIEW_USER = 'viewUser',
  CREATE_POETRY = 'createPoetry',
  DELETE_POETRY = 'deletePoetry',
  UPDATE_POETRY = 'updatePoetry',
  VIEW_DETAIL_POETRY = 'viewDetailPoetry',
  VIEW_POETRY = 'viewPoetry',
  CREATE_AUTHOR = 'createAuthor',
  DELETE_AUTHOR = 'deleteAuthor',
  UPDATE_AUTHOR = 'updateAuthor',
  VIEW_DETAIL_AUTHOR = 'viewDetailAuthor',
  VIEW_AUTHOR = 'viewAuthor',
  CREATE_POETRY_LIST = "createPoetryList",
  UPDATE_POETRY_LIST = "updatePoetryList",
  DELETE_POETRY_LIST = "deletePoetryList",
}