import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from '@/providers'
import "@/app/globals.css";
import Script from "next/script";
import AppLayout from "@/components/layout/AppLayout";
import { TooltipProvider } from "@/components/ui/tooltip";
import SmartSearchButton from '@/components/SmartSearchButton';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "醉诗词",
  description: "Generated by 醉诗词",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <TooltipProvider>
            <AppLayout>
              {children}
              <SmartSearchButton />
            </AppLayout>
          </TooltipProvider>
        </Providers>
        <Script
          src="https://analytics.codefe.cn/script.js"
          async
          defer
          data-website-id="1f32c8c2-8a60-482c-99b7-d6db36cd43a8"
        />
      </body>
    </html>
  );
}
